name: jadwal_kuliah
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  animated_flip_counter: ^0.2.6
  chips_input: ^0.1.0
  collection: ^1.0.0
  dropdown_search: ^5.0.6
  duration_picker: ^1.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_hooks: ^0.18.2+1
  flutter_portal: ^1.1.4
  freezed_annotation: ^2.4.1
  intl: ^0.18.1
  isolate_manager: ^4.1.1
  json_annotation: ^4.8.1
  responsive_builder: ^0.7.0
  responsive_table: ^0.2.0+2
  stacked: ^3.4.0
  stacked_hooks: ^0.2.3
  stacked_services: ^1.1.0
  stacked_themes: ^0.3.12
  supabase_flutter: ^1.10.10
  unicons: ^2.1.1
  url_strategy: ^0.2.0
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
          weight: 400
        - asset: assets/fonts/Oswald-Medium.ttf
          weight: 500
        - asset: assets/fonts/Oswald-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Oswald-Bold.ttf
          weight: 700
