import 'package:flutter/material.dart';

const Color kcPrimaryColor = Color(0xFF293A80);
const Color kcPrimaryColorDark = Color(0xFF010038);
const Color kcSecondaryColor = Color(0xFF537EC5);
const Color kcTertiaryColor = Color(0xFFF39422);
const Color kcBlack = Color(0xFF000000);
const Color kcDarkGreyColor = Color(0xFF1A1B1E);
const Color kcMediumGrey = Color(0xFF474A54);
const Color kcLightGrey = Color.fromARGB(255, 187, 187, 187);
const Color kcVeryLightGrey = Color(0xFFE3E3E3);
const Color kcWhite = Color(0xFFFFFFFF);
const Color kcBackgroundColor = kcWhite;
const Color kcBackgroundColorDark = kcDarkGreyColor;
const Color kcDangerColor = Color(0xFFE74C3C);
const Color kcFontColor = Color(0xFF101828);
const Color kcFontColorDark = Color(0xFFE3E3E3);
const Color kcGreenColor = Color(0xFF00B894);
const Color kcRedColor = Color(0xFFE74C3C);
const Color kcYellowColor = Color(0xFFF9CA24);
const Color kcBlueColor = Color(0xFF0984E3);
const Color kcPurpleColor = Color(0xFF6C5CE7);
